### ISSUE TITLE
Failing on Mac

### ISSUE THREAD

**Issue by wesleyw72** [andrewrothstein/ansible-openjdk#1]
I'm trying to use this on MacOS, as a dependency from the bazelisk role. On the step `add to default path and ease systemd integration...` it fails on mac due to 
`msg": "Destination directory /etc/profile.d does not exist"`. Seems that `/etc/profile.d` doesn't exist on mac which is causing the issue.

**Comment by andrewrothstein** [comment]
yeah, those roles don't really work on a Mac. I mostly just use brew to install software on my Mac. The majority of my roles are really focused towards Linux system level installations. Apologies.
