### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by OnerInce** [andrewrothstein/ansible-openjdk#4]
Currently, it is not possible to install this package, getting following error:

`[WARNING]: - andrewrothstein.alpine-glibc-shim was NOT installed successfully: - sorry, andrewrothstein.alpine-glibc-shim was not found
on https://galaxy.ansible.com/api/.`

**Comment by andrewrothstein** [comment]
Recommend use the andrewrothstein.temurin role. Adoptium publishes musl based JVMs so u won’t need the glibc-shim.
